server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_logs
    static_configs:
      - targets:
          - nginx-gateway  # Use the service name instead of localhost
        labels:
          job: nginx_logs
          __path__: /var/log/nginx/*.log  # Capture all log files