server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_logs
          __path__: /var/log/nginx/access.log
  
  - job_name: nginx_api_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_logs
          __path__: /var/log/nginx/api_access.log
    pipeline_stages:
      - json:
          expressions:
            status_code: status_code
            client_ip: client_ip
            route_decision: route_decision
            is_suspicious_agent: is_suspicious_agent
            has_proxy_headers: has_proxy_headers
  
  - job_name: nginx_honeypot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_logs
          __path__: /var/log/nginx/honeypot_access.log
    pipeline_stages:
      - json:
          expressions:
            status_code: status_code
            client_ip: client_ip
            route_decision: route_decision
            is_suspicious_agent: is_suspicious_agent
            has_proxy_headers: has_proxy_headers